{
 "title": "MySQL Benchmarks",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cloud",
    "query": {
     "query": "label_values(mysql_general_statistics_total_events,cloud)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mysql_general_statistics_total_events{cloud=\"$cloud\"}, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mysql_general_statistics_total_events{cloud=\"$cloud\",cluster=\"${cluster}\"},exported_instance)"
    }
   },
   {
    "name": "run",
    "query": {
     "query": "label_values(mysql_general_statistics_total_events{cloud=\"$cloud\",cluster=\"$cluster\",exported_instance=\"$instance\"},run)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Statistics - Total Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_general_statistics_total_time{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"}"
    }
   ]
  },
  {
   "title": "General Statistics - Total Number of Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_general_statistics_total_events{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"}"
    }
   ]
  },
  {
   "title": "Threads Fairness - Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_thread_fairness_events{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"} "
    }
   ]
  },
  {
   "title": "Threads Fairness - Execution TIme",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_thread_fairness_execution_time{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"}"
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_latency_min{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "mysql_latency_max{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "mysql_latency_avg{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "mysql_latency_percentile{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "mysql_latency_sum{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"}",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_benchmark_result_tps{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\",cluster=\"$cluster\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_benchmark_result_latency{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\",cluster=\"$cluster\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_benchmark_result_threads{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\",cluster=\"$cluster\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_benchmark_result_errors{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\",cluster=\"$cluster\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Reconnects",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_benchmark_result_reconnects{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\",cluster=\"$cluster\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "QPS Reads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_benchmark_result_qps_reads{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\",cluster=\"$cluster\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "QPS Writes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_benchmark_result_qps_writes{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\",cluster=\"$cluster\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "QPS Total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_benchmark_result_qps_total{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\",cluster=\"$cluster\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "QPS Other",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_benchmark_result_qps_other{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\",cluster=\"$cluster\"}",
     "legendFormat": "{{time}}"
    }
   ]
  }
 ]
}