{
 "title": "MySQL Summary",
 "time": { "from": "2021-05-13T11:03:00.000Z", "to": "2021-05-15T21:59:59.000Z" },
 "panels": [
  {
   "title": "Latency Min",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "4",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_min{threads=\"4\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    },
    {
     "title": "8",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_min{threads=\"8\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    },
    {
     "title": "16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_min{threads=\"16\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    },
    {
     "title": "32",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_min{threads=\"32\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    },
    {
     "title": "64",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_min{threads=\"64\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "4",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_max{threads=\"4\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    },
    {
     "title": "8",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_max{threads=\"8\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    },
    {
     "title": "16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_max{threads=\"16\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    },
    {
     "title": "32",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_max{threads=\"32\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    },
    {
     "title": "64",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by(exported_instance) (mysql_latency_max{threads=\"64\"})",
       "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Latency Avg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_avg{threads=\"4\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "8",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_avg{threads=\"8\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "16",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_avg{threads=\"16\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "32",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_avg{threads=\"32\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "64",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_avg{threads=\"64\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  { "title": "Latency 95th Percentile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_percentile{threads=\"4\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "8",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_percentile{threads=\"8\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "16",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_percentile{threads=\"16\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "32",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_percentile{threads=\"32\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "64",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_latency_percentile{threads=\"64\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  { "title": "Transaction Per Second (TPS)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "TPS (4)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_benchmark_result_tps{threads=\"4\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "TPS (8)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_benchmark_result_tps{threads=\"8\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "TPS (16)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_benchmark_result_tps{threads=\"16\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "TPS (32)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_benchmark_result_tps{threads=\"32\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "TPS (64)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_instance) (mysql_benchmark_result_tps{threads=\"64\"})",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  }
 ]
}