{
 "title": "envoy benchmark cockpit",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cloud",
    "label": "Cloud",
    "query": "label_values(wrk2_benchmark_progress,cloud)"
   },
   {
    "name": "instance",
    "label": "Target application",
    "query": "label_values(wrk2_benchmark_progress{cloud=\"$cloud\"}, exported_instance)"
   },
   {
    "name": "job",
    "label": "Benchmark job",
    "query": "label_values(wrk2_benchmark_progress,exported_job)"
   },
   {
    "name": "run",
    "label": "Benchmark run",
    "query": "label_values(wrk2_benchmark_progress{cloud=\"$cloud\",exported_instance=\"$instance\"},run)"
   }
  ]
 },
 "panels": [
  { "title": "ab dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total bytes tranferred (bytes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ab_benchmark_total_bytes_transferred{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\"}"
    }
   ]
  },
  {
   "title": "Transfer rate(Kbytes/sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ab_benchmark_transfer_rate{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\"}"
    }
   ]
  },
  {
   "title": "Total Time taken(s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ab_benchmark_time_taken{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\"}"
    }
   ]
  },
  {
   "title": "Time/req(ms) mean",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ab_benchmark_time_per_request{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\"}"
    }
   ]
  },
  {
   "title": "Total Request/sec mean",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ab_benchmark_requests_per_second{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\"}"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ab_benchmark_failed_request{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\"}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ab_benchmark_complete_request{cloud=\"$cloud\",exported_instance=\"$instance\",run=\"$run\"}"
    }
   ]
  },
  { "title": "wrk dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "wrk2_benchmark_progress{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\",status=\"init\"}",
     "legendFormat": "{{exported_job}}: {{exported_instance}} {{run}} "
    }
   ]
  },
  {
   "title": "Benchmark duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wrk2_benchmark_run_runtime{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\",kind=\"duration\"}"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_progress{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\",status=~\"(init|run)\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Overall RPS (average and current)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_average_rps{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"})",
     "legendFormat": "Average RPS"
    },
    {
     "expr": "sum(wrk2_benchmark_current_rps{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"})",
     "legendFormat": "Current RPS"
    }
   ]
  },
  {
   "title": "Current RPS, per thread",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_current_rps{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}",
     "legendFormat": "{{label}}{{thread}}"
    }
   ]
  },
  {
   "title": "Requested RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_progress{exported_instance=\"$instance\",cloud=\"$cloud\",exported_job=\"$job\",status=\"init\"}",
     "legendFormat": "{{rps}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_average_rps{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"})",
     "legendFormat": "Average RPS"
    },
    {
     "expr": "sum(wrk2_benchmark_current_rps{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"})",
     "legendFormat": "Current RPS"
    }
   ]
  },
  {
   "title": "Average RPS, per thread",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_average_rps{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}",
     "legendFormat": "{{label}}{{thread}}"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wrk2_benchmark_thread_count{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Requests sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_requests{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Responses received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_responses{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Application CPU consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 1, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"envoy\", container!=\"POD\"}",
     "legendFormat": "{{container}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "Cluster node loadavg (1m) per CPU thread",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:node_load1_per_cpu:ratio",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "<hr>\n<center><h5> Benchmark results (updated after a benchmark run has concluded.)</h5></center>"
   },
   "content": "<hr>\n<center><h5> Benchmark results (updated after a benchmark run has concluded.)</h5></center>"
  },
  {
   "title": "started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "wrk2_benchmark_run_runtime{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\",kind=\"start\"} * 1000"
    }
   ]
  },
  {
   "title": "concluded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 27 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "wrk2_benchmark_run_runtime{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\",kind=\"end\"} * 1000"
    }
   ]
  },
  {
   "title": "length",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 1, "x": 4, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "wrk2_benchmark_run_runtime{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\",kind=\"duration\"}"
    }
   ]
  },
  {
   "title": "Avg. TCP reconnects",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_run_average_tcp_reconnect_rate{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Load generator threads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wrk2_benchmark_run_thread_count{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Requested RPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wrk2_benchmark_run_requested_rps{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Latency  percentile histogram (milliseconds)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_latency_ms{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}",
     "legendFormat": "{{p}} percentile"
    }
   ]
  },
  {
   "title": "Requests sent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wrk2_benchmark_run_requests{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total bytes read",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 29 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "wrk2_benchmark_bytes_read{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Effective RPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wrk2_benchmark_run_rps{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}"
    }
   ]
  },
  {
   "title": "URL call counts",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "wrk2_benchmark_url_call_count{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Transport Errors",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 2, "x": 5, "y": 31 },
   "targets": [
    {
     "expr": "wrk2_benchmark_socket_errors{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}",
     "legendFormat": "Socket {{t}}"
    },
    {
     "expr": "wrk2_benchmark_http_errors{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}",
     "legendFormat": "HTTP ret != 200"
    },
    {
     "expr": "wrk2_benchmark_requests_timed_out{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}",
     "legendFormat": "HTTP timeout"
    }
   ]
  },
  {
   "title": "Load generator node(s) per core / thread CPU load",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 31 },
   "targets": [
    {
     "expr": "wrk2_benchmark_run_node_loadavg{kind!=\"raw\",exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}",
     "legendFormat": "{{kind}} {{interval}}"
    }
   ]
  },
  {
   "title": "Detailed latency  percentile histogram (milliseconds)",
   "type": "bargauge",
   "gridPos": { "h": 48, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_latency_detailed_ms{exported_instance=\"$instance\",run=\"$run\",exported_job=\"$job\"}",
     "legendFormat": " {{p}}"
    }
   ]
  }
 ]
}