{
 "title": "wrk2 Summary",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rps",
    "label": "Requested RPS",
    "query": {
     "query": "wrk2_benchmark_summary_latency_ms"
    }
   },
   { "name": "exclude", "label": "Exclude", "query": "No exclusion,run" },
   {
    "name": "exclude_runs",
    "label": "Runs to exclude",
    "query": {
     "query": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center>HTTP/gRPC Benchmark latency summary</center></h1>\n<hr>\n<h3><center>Ampere A1, Graviton2, and x86 (Intel+AMD combined)</center></h3>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": {
    "content": "<br />\n<center><b>0.5 percentile</b></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": {
    "content": "<br />\n<center><b>0.75 percentile</b></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "options": {
    "content": "<br />\n<center><b>0.9 percentile</b></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "options": {
    "content": "<br />\n<center><b>0.99 percentile</b></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "options": {
    "content": "<br />\n<center><b>0.999 percentile</b></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "options": {
    "content": "<br />\n<center><b>0.9999 percentile</b></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "options": {
    "content": "<br />\n<center><b>0.99999 percentile</b></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "options": {
    "content": "<br />\n<center><b>1.0 percentile</b></center>"
   }
  },
  {
   "title": "A1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "G2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 1, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "x86",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 2, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",exported_job=~\"(Intel)|(AMD)\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "{{exported_job}} {{source_run}}"
    }
   ]
  },
  {
   "title": "A1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 3, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "G2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "x86",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",exported_job=~\"(Intel)|(AMD)\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "{{exported_job}} {{source_run}}"
    }
   ]
  },
  {
   "title": "A1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "G2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "x86",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",exported_job=~\"(Intel)|(AMD)\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "{{exported_job}} {{source_run}}"
    }
   ]
  },
  {
   "title": "A1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "G2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 10, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "x86",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",exported_job=~\"(Intel)|(AMD)\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "{{exported_job}} {{source_run}}"
    }
   ]
  },
  {
   "title": "A1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "G2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "x86",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",exported_job=~\"(Intel)|(AMD)\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "{{exported_job}} {{source_run}}"
    }
   ]
  },
  {
   "title": "A1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "G2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "x86",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",exported_job=~\"(Intel)|(AMD)\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "{{exported_job}} {{source_run}}"
    }
   ]
  },
  {
   "title": "A1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "G2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 19, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "x86",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",exported_job=~\"(Intel)|(AMD)\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "{{exported_job}} {{source_run}}"
    }
   ]
  },
  {
   "title": "A1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 21, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "G2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 22, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "x86",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 23, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",exported_job=~\"(Intel)|(AMD)\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "{{exported_job}} {{source_run}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<hr>\n<h3><center>Ampere A1 latency percentiles</center>"
   }
  },
  {
   "title": "0.5 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.75 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "1.0 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",exported_job=\"AmpereA1\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "Peak latencies (1.0 percentile)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "max(wrk2_benchmark_summary_latency_ms{exported_job=\"AmpereA1\",requested_rps=\"$rps\", p=\"1.0\",source_run!~\"$exclude_runs\"}) by (exported_instance,start,end,source_run,value)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<hr>\n<h3><center>AWS Graviton2 latency percentiles</center>"
   }
  },
  {
   "title": "0.5 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.75 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "1.0 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",exported_job=\"Graviton\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "Peak latencies (1.0 percentile)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "max(wrk2_benchmark_summary_latency_ms{exported_job=\"Graviton\",requested_rps=\"$rps\", p=\"1.0\",source_run!~\"$exclude_runs\"}) by (exported_instance,start,end,source_run,value)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<hr>\n<h3><center>AMD latency percentiles</center>"
   }
  },
  {
   "title": "0.5 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",exported_job=\"AMD\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.75 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",exported_job=\"AMD\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",exported_job=\"AMD\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",exported_job=\"AMD\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",exported_job=\"AMD\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",exported_job=\"AMD\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",exported_job=\"AMD\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "1.0 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 14, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",exported_job=\"AMD\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "Peak latencies (1.0 percentile)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "max(wrk2_benchmark_summary_latency_ms{exported_job=\"AMD\",requested_rps=\"$rps\", p=\"1.0\",source_run!~\"$exclude_runs\"}) by (exported_instance,start,end,source_run,value)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "<hr>\n<h3><center>Intel latency percentiles</center>"
   }
  },
  {
   "title": "0.5 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",exported_job=\"Intel\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.75 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",exported_job=\"Intel\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",exported_job=\"Intel\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 6, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",exported_job=\"Intel\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",exported_job=\"Intel\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",exported_job=\"Intel\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",exported_job=\"Intel\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "1.0 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 14, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",exported_job=\"Intel\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "Peak latencies (1.0 percentile)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "expr": "max(wrk2_benchmark_summary_latency_ms{exported_job=\"Intel\",requested_rps=\"$rps\", p=\"1.0\",source_run!~\"$exclude_runs\"}) by (exported_instance,start,end,source_run,value)"
    }
   ]
  }
 ]
}