{
 "title": "Memtier memcached summary dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ops/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort (avg without (run) (memtier_all_stats_totals_ops_sec{exported_job=\"memtier_memcached\",threads=\"4\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_ops_sec{exported_job=\"memtier_memcached\",threads=\"8\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_ops_sec{exported_job=\"memtier_memcached\",threads=\"16\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_ops_sec{exported_job=\"memtier_memcached\",threads=\"32\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Kb/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_kb_sec{exported_job=\"memtier_memcached\",threads=\"4\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_kb_sec{exported_job=\"memtier_memcached\",threads=\"8\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_kb_sec{exported_job=\"memtier_memcached\",threads=\"16\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_kb_sec{exported_job=\"memtier_memcached\",threads=\"32\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Misses/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run) (memtier_all_stats_gets_misses_sec{exported_job=\"memtier_memcached\",threads=\"4\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_gets_misses_sec{exported_job=\"memtier_memcached\",threads=\"8\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_gets_misses_sec{exported_job=\"memtier_memcached\",threads=\"16\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_gets_misses_sec{exported_job=\"memtier_memcached\",threads=\"32\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_latency{exported_job=\"memtier_memcached\",threads=\"4\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_latency{exported_job=\"memtier_memcached\",threads=\"8\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_latency{exported_job=\"memtier_memcached\",threads=\"16\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    },
    {
     "expr": "sort(avg without (run) (memtier_all_stats_totals_latency{exported_job=\"memtier_memcached\",threads=\"32\"}))",
     "legendFormat": "{{cloud}} {{exported_instance}}"
    }
   ]
  }
 ]
}