{
 "title": "Memtier Redis Benchmark",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cloud",
    "query": {
     "query": "label_values(memtier_run_information_seconds{exported_job=\"memtier_redis\"},cloud)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(memtier_run_information_seconds{exported_job=\"memtier_redis\",cloud=\"$cloud\"}, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(memtier_run_information_seconds{exported_job=\"memtier_redis\",cloud=\"$cloud\",cluster=\"$cluster\"},exported_instance)"
    }
   },
   {
    "name": "run",
    "query": {
     "query": "label_values(memtier_run_information_seconds{exported_job=\"memtier_redis\",cloud=\"$cloud\",cluster=\"$cluster\",exported_instance=\"$instance\"},run)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Statistics - Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memtier_run_information_threads{cloud=\"$cloud\", exported_instance=\"$instance\", run=\"$run\"})"
    }
   ]
  },
  {
   "title": "General Statistics - Connections per Thread",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(memtier_run_information_connections_per_thread{cloud=\"$cloud\", exported_instance=\"$instance\", run=\"$run\"})"
    }
   ]
  },
  {
   "title": "General Statistics - Seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(memtier_run_information_seconds{cloud=\"$cloud\", exported_instance=\"$instance\", run=\"$run\"})  "
    }
   ]
  },
  {
   "title": "Totals",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memtier_all_stats_totals_ops_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Ops/s"
    },
    {
     "expr": "sum(memtier_all_stats_totals_hits_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Hits/s"
    },
    {
     "expr": "sum(memtier_all_stats_totals_kb_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Kb/s"
    },
    {
     "expr": "sum(memtier_all_stats_totals_misses_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Misses/s"
    },
    {
     "expr": "avg(memtier_all_stats_totals_latency{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Waits",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memtier_all_stats_waits_ops_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Ops/s"
    },
    {
     "expr": "sum(memtier_all_stats_waits_hits_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Hits/s"
    },
    {
     "expr": "sum(memtier_all_stats_waits_kb_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Kb/s"
    },
    {
     "expr": "sum(memtier_all_stats_waits_misses_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Misses/s"
    },
    {
     "expr": "avg(memtier_all_stats_waits_latency{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Gets",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memtier_all_stats_gets_ops_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Ops/s"
    },
    {
     "expr": "sum(memtier_all_stats_gets_hits_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Hits/s"
    },
    {
     "expr": "sum(memtier_all_stats_gets_kb_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Kb/s"
    },
    {
     "expr": "sum(memtier_all_stats_gets_misses_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Misses/s"
    },
    {
     "expr": "avg(memtier_all_stats_gets_latency{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Sets",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memtier_all_stats_sets_ops_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Ops/s"
    },
    {
     "expr": "sum(memtier_all_stats_sets_hits_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Hits/s"
    },
    {
     "expr": "sum(memtier_all_stats_sets_kb_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Kb/s"
    },
    {
     "expr": "sum(memtier_all_stats_sets_misses_sec{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Misses/s"
    },
    {
     "expr": "avg(memtier_all_stats_sets_latency{cloud=\"$cloud\", cluster=\"$cluster\", exported_instance=\"$instance\", run=\"$run\"})",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}