{
 "title": "Memtier redis summary dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Operations per second", "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 0 } },
  {
   "title": "4 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_ops_sec{exported_job=\"memtier_redis\",threads=\"4\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "8 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_ops_sec{exported_job=\"memtier_redis\",threads=\"8\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "16 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_ops_sec{exported_job=\"memtier_redis\",threads=\"16\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "32 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_ops_sec{exported_job=\"memtier_redis\",threads=\"32\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 9 } },
  {
   "title": "4 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_kb_sec{exported_job=\"memtier_redis\",threads=\"4\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "8 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_kb_sec{exported_job=\"memtier_redis\",threads=\"8\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "16 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_kb_sec{exported_job=\"memtier_redis\",threads=\"16\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "32 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_kb_sec{exported_job=\"memtier_redis\",threads=\"32\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  { "title": "Latency", "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 18 } },
  {
   "title": "4 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_latency{exported_job=\"memtier_redis\",threads=\"4\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "8 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_latency{exported_job=\"memtier_redis\",threads=\"8\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "16 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_latency{exported_job=\"memtier_redis\",threads=\"16\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  },
  {
   "title": "32 Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(avg without (run,process) (memtier_all_stats_totals_latency{exported_job=\"memtier_redis\",threads=\"32\"}))",
     "legendFormat": "{{cloud}} <br /> {{exported_instance}}"
    }
   ]
  }
 ]
}